### ISSUE TITLE
Default values for active, ticked, featured not set

### ISSUE THREAD

**Issue by londonreturns** [londonreturns/Raise-Rally#69]
Intended Behavior:
When creating a new item in the system, the default value for the "active" attribute should be set to "true" or "active" by default, indicating that the item is active and visible.
Similarly, the default value for the "featured" attribute should be set to "false" or "not featured" by default, indicating that the item is not featured prominently.
The "ticked" attribute, if applicable, should have a default value that reflects its initial state (e.g., "true" for ticked items or "false" for non-ticked items).

Set default values:
- Active - true
- Featured - false
- Verified - false

Actual Behavior (Bug):
When a new item is created, the default value for the "active" attribute is not set or is set incorrectly, leading to confusion about the item's visibility status.
The "featured" attribute defaults to an unexpected value (e.g., "true" instead of "false"), causing items to appear as featured when they shouldn't be.
The "ticked" attribute, if present, may have an incorrect default value that does not align with the item's actual state, leading to inaccurate representation or functionality.
<img width="284" alt="image" src="https://github.com/londonreturns/Raise-Rally/assets/76239421/bae0394c-bd92-40e5-93f2-0699210b8b83">

**Comment by iamrubynzzz** [comment]
The default value for active, featured and ticked has been set.
