### ISSUE TITLE
User can see disabled products and disabled company's products

### ISSUE THREAD

**Issue by londonreturns** [londonreturns/Raise-Rally#73]
Intended Behavior:
When a product is disabled in the system, it should not be visible to regular users browsing the product catalog or searching for products.
Similarly, if an entire company's products are disabled (e.g., the company's account is disabled), none of their products should be visible to users.

Actual Behavior (Bug):
Disabled products are still visible to users in the product catalog or search results, leading to confusion and potentially allowing users to interact with products that should not be accessible.
If a company's account is disabled, its products remain visible to users, contradicting the intended behavior of hiding products associated with disabled companies.

**Comment by iamrubynzzz** [comment]
Disable product and company has been hidden for the backer.
