### ISSUE TITLE
Backers should not be able to fund products which are past end date

### ISSUE THREAD

**Issue by londonreturns** [londonreturns/Raise-Rally#75]
Intended Behavior:
Backers should only be able to fund products that are currently active and within their funding period.
Products that have exceeded their funding period or are otherwise considered "out of date" should not be available for funding by backers.

Actual Behavior (Bug):
Backers can still fund products that have passed their funding period or are otherwise considered out of date.
This allows backers to contribute to projects that may no longer be viable or available for funding, leading to potential confusion and wasted resources.

**Comment by iamrubynzzz** [comment]
Validation has been added in contribution.
