### ISSUE TITLE
User name, and company description length max length not defined

### ISSUE THREAD

**Issue by londonreturns** [londonreturns/Raise-Rally#76]
Intended Behavior:
Usernames and company descriptions should have a defined maximum length to ensure data consistency and prevent issues with data storage and display.
The system should enforce this maximum length when users are creating or updating their profiles, prompting them to adhere to the specified character limit.

Actual Behavior (Bug):
The maximum length for usernames and company descriptions is not defined or enforced in the system.
Users can input usernames and company descriptions of any length, potentially leading to issues with database storage, UI rendering, or data inconsistency.
Without a maximum length constraint, users may inadvertently input excessively long usernames or descriptions, which can impact the overall user experience and system performance.

**Comment by iamrubynzzz** [comment]
The maximum length for usernames and description has been set to 50 and 100 respectively.
